# Generated by Django 4.2.7 on 2023-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
