# Generated by Django 4.2.7 on 2023-11-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_first_name_alter_schedule_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
