# Generated by Django 4.2.7 on 2023-11-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_schedule_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule',
        ),
        migrations.DeleteModel(
            name='schedule_category',
        ),
    ]
